site_name: Documentação Mamutes do Cerrado

nav:
  - Apresentação: index.md

  - Atas:
      - Capacitação:
          - Ata 1: "atas-reuniao/capacitacao/ata-reuniao-cap-1.md"
          - Ata 2: "atas-reuniao/capacitacao/ata-reuniao-cap-2.md"
          - Ata 3: "atas-reuniao/capacitacao/ata-reuniao-cap-3.md"
          - Ata 4: "atas-reuniao/capacitacao/ata-reuniao-cap-4.md"
          - Ata 5: "atas-reuniao/capacitacao/ata-reuniao-cap-5.md"
          - Ata 6: "atas-reuniao/capacitacao/ata-reuniao-cap-6.md"
          - Ata 7: "atas-reuniao/capacitacao/ata-reuniao-cap-7.md"
          - Ata 8: "atas-reuniao/capacitacao/ata-reuniao-cap-8.md"
          - Ata 9: "atas-reuniao/capacitacao/ata-reuniao-cap-9.md"

      - Cliente:
          - Ata 1: "atas-reuniao/cliente/ata-reuniao-1.md"
          - Ata 2: "atas-reuniao/cliente/ata-reuniao-2.md"
          - Ata 3: "atas-reuniao/cliente/ata-reuniao-3.md"
          - Ata 4: "atas-reuniao/cliente/ata-reuniao-4.md"
          - Ata 5: "atas-reuniao/cliente/ata-reuniao-5.md"
          - Ata 6: "atas-reuniao/cliente/ata-reuniao-6.md"
          - Ata 7: "atas-reuniao/cliente/ata-reuniao-7.md"
          - Ata 8: "atas-reuniao/cliente/ata-reuniao-8.md"
          - Ata 9: "atas-reuniao/cliente/ata-reuniao-9.md"

      - Equipe:
          - Ata 1: "atas-reuniao/equipe/ata-reuniao-1-equipe.md"
          - Ata 2: "atas-reuniao/equipe/ata-reuniao-2-equipe.md"
          - Ata 3: "atas-reuniao/equipe/ata-reuniao-3-equipe.md"
          - Ata 4: "atas-reuniao/equipe/ata-reuniao-4-equipe.md"
          - Ata 5: "atas-reuniao/equipe/ata-reuniao-5-equipe.md"
          - Ata 6: "atas-reuniao/equipe/ata-reuniao-6-equipe.md"
          - Ata 7: "atas-reuniao/equipe/ata-reuniao-7-equipe.md"
          - Ata 8: "atas-reuniao/equipe/ata-reuniao-8-equipe.md"
          - Ata 9: "atas-reuniao/equipe/ata-reuniao-9-equipe.md"
          - Ata 10: "atas-reuniao/equipe/ata-reuniao-10-equipe.md"
          - Ata 11: "atas-reuniao/equipe/ata-reuniao-11-equipe.md"
          - Ata 12: "atas-reuniao/equipe/ata-reuniao-12-equipe.md"
          - Ata 13: "atas-reuniao/equipe/ata-reuniao-13-equipe.md"

  - Documentação:
      - Visão Geral: "documento-visao/documento-visao.md"
      - Arquitetura: "documento-arquitetura/documento-arquitetura.md"
      - Requisitos: "documento-requisitos/documento-requisitos.md"
      - Eletrônica: "documento-eletronica/documento-eletronica.md"
      - Estrutura: "documento-estrutura/documento-estrutura.md"
      - Firmware: "documento-firmware/documento-firmware.md"
      - Testes: 
          - Plano de Testes: "documento-plano-testes/documento-plano-testes.md"
          - Testes de Integração: "documento-Testes-Integracao/documento-Testes-Integracao.md"
          - Testes Unitários: "documento-Testes-Unitarios/documento-Testes-Unitarios.md"

  - Links: "links/links.md"

theme:
  name: material
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking

  palette:
    - scheme: default
      primary: white
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Mudar para modo escuro

    - scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Mudar para modo claro

  font:
    text: Roboto
    code: Roboto Mono

extra_css:
  - stylesheets/styles.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css

styles_css:
  - view/css/styles.css
